# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccac86906c8ee0b405fdf7e1a98b1d03fb2e6a841219ea79b725e7d614d258216683c0b56103dbec5b3907e7e8dc7b2f2254d29b0894347c6d44a116fa5ed41a

test:
  secret_key_base: 1356d09e630368ebc03a0655660fafc5b7b864b462b4dabdae3d6640e65698dc855366ae544faac1a720493f6e90e313795a0aeaf7e303c1d56afaa3bb050a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
